### ISSUE TITLE
Generate materials for BASIC SEVA v1.0 build

### ISSUE THREAD

**Issue by hainesm6** [LondonBiofoundry/basicsynbio#154]
## Tasks

- [x] Competent cells
- [x] Order primers to correct BS_5xx, BS_x7x and BS_x8x
- [x] Order additional sequencing primer for BS_x7x
- [x] Prepped and sequence-validated initial modules:
     - [x] BS_1xx
     - [x] BS_2xx
     - [x] BS_3xx
     - [x] BS_4xx
     - [x] BS_5axx
     - [x] BS_6xx
     - [x] B405
     - [x] B407
     - [x] B408
     - [x] BS_x6x
     - [x] BS_x7x
     - [x] BS_x7x_TS
     - [x] BS_x9x

## Comments
- BS_x5x postponed/cancelled given the following mutations: 1203_1204insC, 3891_3895insG. There is also a further mutation (670_671insGTA) however, this is not within the SEVA region for rsf1010 or another annotated region of the plasmid and therefore doesn't require correction.
- BS_5xx may not confer resistance to 10 μg/mL tetracycline in DH5α, yielding <10% of the colonies obtained with a variant (BS_5axx) containing a 248I>S mutation in the tetracycline efflux transporter. This variant will be used instead.
- BS_x8x appears too burdensome for DH5α with SEVA_Ap. This was characterised by a large number of small colonies following transformation of a circularised PCR product likely containing this sequence. Notably a ColE1 variant ([MN913428.1](https://www.ncbi.nlm.nih.gov/nuccore/MN913428)) with a single substitution mutation compared to SEVA_pUC (SEVA_pUC_419T>A) was identified from the original BS_x8x prep. ColE1 is present at signficiantly [lower copies](https://blog.addgene.org/plasmid-101-origin-of-replication) compared to pUC and the fact that pUC combined with SEVA_Ap is burdensome suggests x8x constructs will not be robust. As such, x8x constructs were dropped from this collection.
